<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.0.10" />
    <PackageReference Include="DotNetZip.Original" Version="2025.1.26" />
    <PackageReference Include="Joveler.Compression.ZLib" Version="4.1.0" />
    <PackageReference Include="K4os.Compression.LZ4" Version="1.2.16" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.2-beta1" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.5" />
    <PackageReference Include="System.Resources.Extensions" Version="6.0.0" />
    <ProjectReference Include="CTFAK-Nuclear/Core/CTFAK.Core/CTFAK.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="../exporter/src/Exporter.cs" Link="Exporter.cs" />
    <Compile Include="../exporter/src/BaseExporter.cs" Link="BaseExporter.cs" />
    <Compile Include="../exporter/src/PakBuilder.cs" Link="PakBuilder.cs" />
    <Compile Include="../exporter/src/Compiler.cs" Link="Compiler.cs" />
    <Compile Include="../exporter/src/BuildType.cs" Link="BuildType.cs" />
    <Compile Include="../exporter/src/Utilites.cs" Link="Utilites.cs" />
    <Compile Include="../exporter/src/CollisionMaskBuilder.cs" Link="CollisionMaskBuilder.cs" />
    <Compile Include="../exporter/src/IconFactory.cs" Link="IconFactory.cs" />
    <Compile Include="../exporter/src/Exporters/**/*.cs" LinkBase="Exporters" />
    <Compile Include="../exporter/src/Events/**/*.cs" LinkBase="Events" />
    <Compile Include="../exporter/src/Utils/**/*.cs" LinkBase="Utils" />
  </ItemGroup>
</Project>
